# Generated by Django 3.0.4 on 2020-03-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_name', models.CharField(max_length=200)),
                ('Flight_timing', models.CharField(max_length=200)),
                ('Flight_destination', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Air_hostess', models.CharField(max_length=200)),
                ('Pilot', models.CharField(max_length=200)),
                ('Registered_passengers', models.IntegerField(default=0)),
                ('Flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Details')),
            ],
        ),
    ]
