# Generated by Django 3.0.4 on 2020-03-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20200324_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
        migrations.RenameField(
            model_name='crew',
            old_name='details',
            new_name='Flight',
        ),
    ]
