# Generated by Django 3.0.4 on 2020-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20200324_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domestic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oneway', models.TextField(verbose_name='Return')),
                ('From', models.CharField(choices=[('1', 'Karachi-Jinnah Intl. (KHI)'), ('2', 'Bahawalpur(BHV)'), ('3', 'Chitral(CJL)'), ('4', 'Dalbandin(DBA)'), ('5', 'Dera Ghazi Khan Intl(DEA)'), ('6', 'Dera Ismail khan(DSK)'), ('7', 'Faislabad Intl(LYP)'), ('8', 'Gilgit(GIL)'), ('9', 'Gwadar Intl.(GWD)'), ('10', 'Islamabad Intl(ISB)'), ('11', 'Lahore Intl (LHE)'), ('12', 'Moenjodaro(MJD)'), ('13', 'Multan Intl.(MUX)'), ('14', 'Nawabshah Airport(WNS)'), ('15', 'Panjgur(PJG)'), ('16', 'Peshawar Intl(PEW)'), ('17', 'Quetta Intl(UET)'), ('18', 'Rahim Yar khan(RYK)'), ('19', 'Sialkot Intl(SKT)'), ('20', 'Skardu Intl(SKT)'), ('21', 'Sukkur(SKZ)'), ('22', 'Turbat Intl(TUK)'), ('23', 'Zhob(PZH)'), ('24', 'Select')], default='24', max_length=200)),
                ('To', models.CharField(choices=[('1', 'Karachi-Jinnah Intl. (KHI)'), ('2', 'Bahawalpur(BHV)'), ('3', 'Chitral(CJL)'), ('4', 'Dalbandin(DBA)'), ('5', 'Dera Ghazi Khan Intl(DEA)'), ('6', 'Dera Ismail khan(DSK)'), ('7', 'Faislabad Intl(LYP)'), ('8', 'Gilgit(GIL)'), ('9', 'Gwadar Intl.(GWD)'), ('10', 'Islamabad Intl(ISB)'), ('11', 'Lahore Intl (LHE)'), ('12', 'Moenjodaro(MJD)'), ('13', 'Multan Intl.(MUX)'), ('14', 'Nawabshah Airport(WNS)'), ('15', 'Panjgur(PJG)'), ('16', 'Peshawar Intl(PEW)'), ('17', 'Quetta Intl(UET)'), ('18', 'Rahim Yar khan(RYK)'), ('19', 'Sialkot Intl(SKT)'), ('20', 'Skardu Intl(SKT)'), ('21', 'Sukkur(SKZ)'), ('22', 'Turbat Intl(TUK)'), ('23', 'Zhob(PZH)'), ('24', 'Select')], default='24', max_length=200)),
                ('Date', models.CharField(default='Enter Departure Date', max_length=200)),
                ('Return', models.CharField(default='Enter Return Date', max_length=200)),
                ('Cabin', models.CharField(choices=[('1', 'Select'), ('2', 'Economy'), ('3', 'Executive Economy'), ('4', 'Business')], default='1', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oneway', models.TextField(verbose_name='Return')),
                ('From', models.CharField(default='From: Airport & City', max_length=200)),
                ('To', models.CharField(default='To: Airport & City', max_length=200)),
                ('Date', models.CharField(default='Enter Departure Date', max_length=200)),
                ('Return', models.CharField(default='Enter Return Date', max_length=200)),
                ('Cabin', models.CharField(choices=[('1', 'Select'), ('2', 'Economy'), ('3', 'Executive Economy'), ('4', 'Business')], default='1', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
