# Generated by Django 3.0.4 on 2020-03-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20200325_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domestic',
            name='Oneway',
        ),
        migrations.RemoveField(
            model_name='international',
            name='Oneway',
        ),
        migrations.AddField(
            model_name='domestic',
            name='Type',
            field=models.CharField(choices=[('1', 'Select'), ('2', 'Return'), ('3', 'Oneway')], default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='international',
            name='Type',
            field=models.CharField(choices=[('1', 'Select'), ('2', 'Return'), ('3', 'Oneway')], default='1', max_length=100),
        ),
    ]
