# Generated by Django 3.0.4 on 2020-03-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20200325_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domestic',
            name='Cabin',
        ),
        migrations.RemoveField(
            model_name='domestic',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='domestic',
            name='From',
        ),
        migrations.RemoveField(
            model_name='domestic',
            name='Return',
        ),
        migrations.RemoveField(
            model_name='domestic',
            name='To',
        ),
        migrations.RemoveField(
            model_name='international',
            name='Cabin',
        ),
        migrations.RemoveField(
            model_name='international',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='international',
            name='From',
        ),
        migrations.RemoveField(
            model_name='international',
            name='Return',
        ),
        migrations.RemoveField(
            model_name='international',
            name='To',
        ),
    ]
