# Generated by Django 3.0.4 on 2020-03-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_auto_20200325_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='domestic',
            name='Cabin',
            field=models.CharField(choices=[('1', 'Select'), ('2', 'Economy'), ('3', 'Executive Economy'), ('4', 'Business')], default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='domestic',
            name='Date',
            field=models.CharField(default='Enter Date', max_length=200),
        ),
        migrations.AddField(
            model_name='domestic',
            name='From',
            field=models.CharField(choices=[('1', 'Karachi-Jinnah Intl. (KHI)'), ('2', 'Bahawalpur(BHV)'), ('3', 'Chitral(CJL)'), ('4', 'Dalbandin(DBA)'), ('5', 'Dera Ghazi Khan Intl(DEA)'), ('6', 'Dera Ismail khan(DSK)'), ('7', 'Faislabad Intl(LYP)'), ('8', 'Gilgit(GIL)'), ('9', 'Gwadar Intl.(GWD)'), ('10', 'Islamabad Intl(ISB)'), ('11', 'Lahore Intl (LHE)'), ('12', 'Moenjodaro(MJD)'), ('13', 'Multan Intl.(MUX)'), ('14', 'Nawabshah Airport(WNS)'), ('15', 'Panjgur(PJG)'), ('16', 'Peshawar Intl(PEW)'), ('17', 'Quetta Intl(UET)'), ('18', 'Rahim Yar khan(RYK)'), ('19', 'Sialkot Intl(SKT)'), ('20', 'Skardu Intl(SKT)'), ('21', 'Sukkur(SKZ)'), ('22', 'Turbat Intl(TUK)'), ('23', 'Zhob(PZH)'), ('24', 'Select')], default='24', max_length=200),
        ),
        migrations.AddField(
            model_name='domestic',
            name='To',
            field=models.CharField(choices=[('1', 'Karachi-Jinnah Intl. (KHI)'), ('2', 'Bahawalpur(BHV)'), ('3', 'Chitral(CJL)'), ('4', 'Dalbandin(DBA)'), ('5', 'Dera Ghazi Khan Intl(DEA)'), ('6', 'Dera Ismail khan(DSK)'), ('7', 'Faislabad Intl(LYP)'), ('8', 'Gilgit(GIL)'), ('9', 'Gwadar Intl.(GWD)'), ('10', 'Islamabad Intl(ISB)'), ('11', 'Lahore Intl (LHE)'), ('12', 'Moenjodaro(MJD)'), ('13', 'Multan Intl.(MUX)'), ('14', 'Nawabshah Airport(WNS)'), ('15', 'Panjgur(PJG)'), ('16', 'Peshawar Intl(PEW)'), ('17', 'Quetta Intl(UET)'), ('18', 'Rahim Yar khan(RYK)'), ('19', 'Sialkot Intl(SKT)'), ('20', 'Skardu Intl(SKT)'), ('21', 'Sukkur(SKZ)'), ('22', 'Turbat Intl(TUK)'), ('23', 'Zhob(PZH)'), ('24', 'Select')], default='24', max_length=200),
        ),
        migrations.AddField(
            model_name='international',
            name='Cabin',
            field=models.CharField(choices=[('1', 'Select'), ('2', 'Economy'), ('3', 'Executive Economy'), ('4', 'Business')], default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='international',
            name='Date',
            field=models.CharField(default='Enter Date', max_length=200),
        ),
        migrations.AddField(
            model_name='international',
            name='From',
            field=models.CharField(default='From: Airport & City', max_length=100),
        ),
        migrations.AddField(
            model_name='international',
            name='To',
            field=models.CharField(default='To: Airport & City', max_length=100),
        ),
    ]
