# Generated by Django 3.0.4 on 2020-03-27 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_auto_20200325_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Passenegers_limit', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='domestic',
            name='Date',
            field=models.CharField(default='MM/DD/YEAR', max_length=200),
        ),
        migrations.AlterField(
            model_name='international',
            name='Date',
            field=models.CharField(default='MM/DD/YEAR', max_length=200),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Starting_time', models.DateTimeField()),
                ('Destination_time', models.DateTimeField()),
                ('Destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destination_airport', to='flights.Airport')),
                ('Starting_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Starting_airport', to='flights.Airport')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='flights.Crew')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot', to='flights.Pilot')),
            ],
        ),
    ]
