# Generated by Django 3.0.4 on 2020-04-01 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0011_auto_20200331_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Passeneger_flight', to='flights.Flight')),
            ],
        ),
    ]
