# Generated by Django 3.0.4 on 2020-04-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
